package com.lcwd.servlets;

import java.io.IOException;
import java.io.PrintWriter;

import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

//@WebServlet(name = "MainServlet", urlPatterns = "/main")
public class MainServlet extends HttpServlet {

	@Override
	protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
		System.out.println("this is main servelet page:");
		
		PrintWriter writer = resp.getWriter();
		
		writer.println("<h1> This is main servlet </h1> ");

		writer.println("<p> Welcome to main servlet page this page is generated by servlet.[java program] </p> ");
		
		
		
		
		
		
		
		
	}

}
